export const projects = [
    {
      id: 1,
      title: "Baby Bundles",
      des: "Ecommervce website for baby needs",
      img: "../public/babybuntle.png",
      link: "",
      liveLink: "https://elitemediator.shop/",
    },
    {
      id: 2,
      title: "Mediflow",
      des: "An Ecommerce app with all the functionalities of a typical ecommerce platform",
      img: "../public/Mediflow.png",
      link: "https://github.com/Arjunkumar1877/Wood-palace-Ecommerce.git",
      videoLink: "https://youtu.be/J0lwRpYx6jc",
      liveLink: "http://woodpalace.live/user",
    },
    {
      id: 3,
      title: "Pdf uploading app",
      des: "Users can generate strong passwords, save and manage them securely",
      img: "../public/PedfApp.png",
      link: "https://github.com/Arjunkumar1877/Password-Manager.git",
      videoLink: "",
      liveLink: "https://pm-client-brocodes-projects-0d98f139.vercel.app/",
    },
    {
      id: 4,
      title: "Olx clone Application",
      des: "A personal blog that reflects my skills and showcases all my projects",
      img: "../public/olx.png",
      link: "https://github.com/Arjunkumar1877/MERN-BLOG.git",
      liveLink: "https://olx-clone-x8sj.onrender.com",
    },
    {
      id: 5,
      title: "Netflix clone",
      des: "Users can buy, sell, and rent properties on this real estate platform",
      img: "../public/netflix.png",
      link: "https://github.com/Arjunkumar1877/MERN_realestate.git",
      videoLink: "https://youtu.be/lG1OTdqoVAY",
      liveLink: "https://netflix-rnax.onrender.com",
    },
    {
      id: 6,
      title: "Way to nikkah Clone",
      des: "A private one-to-one chat application for secure conversations",
      img: "../public/waytonikkah.png",
      link: "https://github.com/Arjunkumar1877/MERN-CHAT-APP.git",
      liveLink: "https://way-to-nikkah.onrender.com",
    },
    {
      id: 7,
      title: "Zoomify a Video Calling App",
      des: "A simple video calling application with conference and one-to-one call support",
      img: "/zoomify.png",
      link: "https://github.com/Arjunkumar1877/Zego-Zoomify.git",
      videoLink: "",
      liveLink: "https://zego-zoomify.vercel.app/",
    },
    {
      id: 8,
      title: "An X App Clone",
      des: "A fullstack clone of the X (Twitter) app using Next.js. With minimal functionalities of a X app",
      img: "/Xapp.png",
      link: "https://github.com/Arjunkumar1877/x-next-app.git",
      videoLink: "",
      liveLink: "https://x-next-app.vercel.app/",
    },
    {
      id: 9,
      title: "A Fullstack Food Delivery App",
      des: "A complete food delivery app with ordering and payment features",
      img: "/Fooddelivery.png",
      link: "https://github.com/Arjunkumar1877/FOOD-DELIVERY-APP.git",
      videoLink: "https://youtu.be/2WNX-d6Dmpo",
      liveLink: "",
    },
    {
      id: 10,
      title: "A Fullstack Ecommerce App",
      des: "A fullstack ecommerce platform for purchasing dresses and apparel",
      img: "/Ecommerce.png",
      link: "https://github.com/Arjunkumar1877/MERN-ECOMMERCE.git",
      videoLink: "https://youtu.be/JdWpFinceYk",
      liveLink: "",
    },
    {
      id: 11,
      title: "An Amazon Frontend Clone",
      des: "A clone of the Amazon frontend with all major pages designed",
      img: "/Amazone.png",
      link: "https://github.com/Arjunkumar1877/ECOMMERCE-APP-STATIC.git",
      videoLink: "",
      liveLink: "https://amazon-clone-1877.netlify.app/",
    },
    {
      id: 12,
      title: "A Facebook Frontend Clone",
      des: "A frontend clone of Facebook with a beautiful and responsive design",
      img: "/Facebook.png",
      link: "https://github.com/Arjunkumar1877/react-facebook--clone.git",
      videoLink: "",
      liveLink: "https://fb-app-1877.netlify.app/",
    },
    {
      id: 13,
      title: "A Fullstack Quiz App",
      des: "A quiz app where users can take and create quizzes using Next.js",
      img: "/Quiz.png",
      link: "https://github.com/Arjunkumar1877/Next-js-Quiz-app.git",
      videoLink: "",
      liveLink: "",
    },
    {
      id: 14,
      title: "An OLX Clone App",
      des: "An OLX clone application with minimal functionalities",
      img: "/Olx.png",
      link: "https://github.com/Arjunkumar1877/OLX-clone-.git",
      videoLink: "",
      liveLink: "https://olx-clone-iota-seven.vercel.app/",
    },
    {
      id: 15,
      title: "A Netflix Frontend Clone",
      des: "A frontend design of the Netflix application",
      img: "/Netflix.png",
      link: "https://github.com/Arjunkumar1877/NetflixClone.git",
      videoLink: "",
      liveLink: "https://netflix-clone-brocodes-projects-0d98f139.vercel.app/",
    },
  ];
  